# InfluxDB + Grafana compose file. 
# With data persistency
influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
  environment:
    INFLUXDB_HTTP_AUTH_ENABLED: "false"
  volumes:
    - /tmp/docker/influxdb/data:/var/lib/influxdb

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  user: "0"
  links:
    - influxdb
  volumes:
    - /tmp/docker/grafana/data:/var/lib/grafana